services:
  api:
    build:
      dockerfile: fastapi/Dockerfile
    volumes:
      - ./src/fastapi:/src
      - ./sqlite-data/:/data/
    networks:
      - chatbot-net

  gradio:
    build:
      dockerfile: gradio/Dockerfile
    ports:
      - 80:7860
    volumes:
      - ./src/gradio:/src
      - ./sqlite-data/:/data/
    networks:
      - chatbot-net

  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    volumes:
      - ./ollama-models:/root/.ollama/models
    networks:
      - chatbot-net

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - ./redis-data:/data
    networks:
      - chatbot-net

networks:
  chatbot-net:
    driver: bridge