services:
  api:
    build:
      dockerfile: fastapi/Dockerfile
    ports:
      - 5005:5005
    volumes:
      - ./src:/src
    networks:
      - chatbot-net

  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    ports:
      - 11434:11434
    volumes:
      - ./ollama-models:/root/.ollama/models
    networks:
      - chatbot-net
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]

networks:
  chatbot-net:
    driver: bridge