services:
  api:
    build:
      dockerfile: fastapi/Dockerfile
    ports:
      - 5005:5005
    volumes:
      - ./src:/src
    networks:
      - chatbot-net

  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    ports:
      - 11434:11434
    volumes:
      - ./ollama-models:/root/.ollama/models
    networks:
      - chatbot-net

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./redis-data:/data
    networks:
      - chatbot-net

  sqlite-web:
    image: coleifer/sqlite-web
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./sqlite-data/data.db:/data/data.db
    entrypoint: ["sqlite_web", "/data/data.db"]
    networks:
      - chatbot-net

networks:
  chatbot-net:
    driver: bridge